---
kind: pipeline
name: crio

trigger:
  branch:
    - main

clone:
  disable: true

steps:
  - name: fetch
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-git:1.0
    settings:
      proxy:
        from_secret: SOCKS5_PROXY

  - name: scripts-amd64
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/alpine:3
    environment:
      BUILD_ARCH: amd64
    commands:
      - mkdir -p dist/linux-$BUILD_ARCH
      - cp -r scripts dist/linux-$BUILD_ARCH/
      - cp -r service dist/linux-$BUILD_ARCH/
    depends_on:
      - fetch

  - name: crio-amd64
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/curl:alpine
    environment:
      BUILD_ARCH: amd64
      BUILD_VERSION: v1.30.8
    commands:
      - sh hack/crio.sh
    depends_on:
      - scripts-amd64

  - name: tgz-amd64
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/alpine:3
    environment:
      BUILD_ARCH: amd64
      BUILD_VERSION: v1.30.8
    commands:
      - mkdir -p .tmp
      - tar zcvf .tmp/ansible-crio-$BUILD_VERSION-$BUILD_ARCH.tgz -C dist/linux-$BUILD_ARCH/ .
    depends_on:
      - scripts-amd64
      - crio-amd64

  - name: scripts-arm64
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/alpine:3
    environment:
      BUILD_ARCH: arm64
    commands:
      - mkdir -p dist/linux-$BUILD_ARCH
      - cp -r scripts dist/linux-$BUILD_ARCH/
      - cp -r service dist/linux-$BUILD_ARCH/
    depends_on:
      - fetch

  - name: crio-arm64
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/curl:alpine
    environment:
      BUILD_ARCH: arm64
      BUILD_VERSION: v1.30.8
    commands:
      - sh hack/crio.sh
    depends_on:
      - scripts-arm64

  - name: tgz-arm64
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/alpine:3
    environment:
      BUILD_ARCH: arm64
      BUILD_VERSION: v1.30.8
    commands:
      - mkdir -p .tmp
      - tar zcvf .tmp/ansible-crio-$BUILD_VERSION-$BUILD_ARCH.tgz -C dist/linux-$BUILD_ARCH/ .
    depends_on:
      - scripts-arm64
      - crio-arm64

  - name: minio
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-minio:1.0
    environment:
      S3_ACCESS_KEY:
        from_secret: S3_ACCESS_KEY_ALIYUN
      S3_SECRET_KEY:
        from_secret: S3_SECRET_KEY_ALIYUN
    commands:
      - ping cache.ali.wodcloud.com -c 1
      - mc alias set aliyun --api=S3v4 https://cache.ali.wodcloud.com $S3_ACCESS_KEY $S3_SECRET_KEY
      - mc cp install.sh aliyun/kubernetes/ansible/ansible-crio.sh
      - mc cp uninstall.sh aliyun/kubernetes/ansible/ansible-crio-uninstall.sh
      - mc cp --recursive .tmp/ansible-crio-*.tgz aliyun/kubernetes/ansible/
    depends_on:
      - tgz-amd64
      - tgz-arm64

---
kind: secret
name: SOCKS5_PROXY
get:
  name: SOCKS5_PROXY
  path: devops-secrets

---
kind: secret
name: S3_ACCESS_KEY_ALIYUN
get:
  name: S3_ACCESS_KEY_ALIYUN
  path: devops-secrets

---
kind: secret
name: S3_SECRET_KEY_ALIYUN
get:
  name: S3_SECRET_KEY_ALIYUN
  path: devops-secrets
